import { Skill } from '@/types/skill';

export const skills: Skill[] = [
  {
    imageUrl: 'https://cdn.simpleicons.org/html5',
    title: 'HTML 5',
    color: '#e34f26',
    segment: 'frontend',
    level: 92,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/css3',
    title: 'CSS 3',
    color: '#1573b7',
    segment: 'frontend',
    level: 92,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/javascript',
    title: 'Javascript',
    color: '#f8df1d',
    segment: 'frontend',
    level: 93,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/typescript',
    title: 'Typescript',
    color: '#3179c6',
    segment: 'frontend',
    level: 94,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/react',
    title: 'React',
    color: '#61dafc',
    segment: 'frontend',
    level: 97,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/nextdotjs/FFF',
    title: 'Next.js',
    color: '#fff',
    segment: 'frontend',
    level: 95,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/angular/DD0031',
    title: 'Angular',
    color: '#dd0031',
    segment: 'frontend',
    level: 78,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/vuedotjs',
    title: 'Vue.js',
    color: '#4fc08d',
    segment: 'frontend',
    level: 67,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/astro',
    title: 'Astro.js',
    color: '#bc53ef',
    segment: 'frontend',
    level: 70,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/nodedotjs',
    title: 'Node.js',
    color: '#60a04e',
    segment: 'backend',
    level: 88,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/nestjs',
    title: 'Nest.js',
    color: '#e0234e',
    segment: 'backend',
    level: 87,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/php',
    title: 'PHP',
    color: '#777bb4',
    segment: 'backend',
    level: 67,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/go',
    title: 'Go',
    color: '#00add8',
    segment: 'backend',
    level: 52,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/dotnet',
    title: '.Net',
    color: '#512bd4',
    segment: 'backend',
    level: 74,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/react',
    title: 'React Native',
    color: '#61dafc',
    segment: 'mobile',
    level: 94,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/expo/FFF',
    title: 'Expo',
    color: '#fff',
    segment: 'mobile',
    level: 93,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/ionic',
    title: 'Ionic',
    color: '#3880ff',
    segment: 'mobile',
    level: 67,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/flutter',
    title: 'Flutter',
    color: '#02579c',
    segment: 'mobile',
    level: 49,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/jest',
    title: 'Jest',
    color: '#c21326',
    segment: 'test',
    level: 89,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/vitest',
    title: 'Vitest',
    color: '#6fa017',
    segment: 'test',
    level: 69,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/testinglibrary',
    title: 'Testing Library',
    color: '#e43333',
    segment: 'test',
    level: 82,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/cypress',
    title: 'Cypress',
    color: '#6ad3a7',
    segment: 'test',
    level: 72,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/postgresql',
    title: 'PostgreSQL',
    color: '#4169e1',
    segment: 'database',
    level: 93,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/mysql',
    title: 'MySQL',
    color: '#4479a2',
    segment: 'database',
    level: 87,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/mongodb',
    title: 'Mongo DB',
    color: '#48a248',
    segment: 'database',
    level: 80,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/firebase',
    title: 'Firebase',
    color: '#dd2c00',
    segment: 'database',
    level: 75,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/redis',
    title: 'Redis',
    color: '#ff4438',
    segment: 'database',
    level: 89,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/sqlite',
    title: 'SQlite',
    color: '#003b58',
    segment: 'database',
    level: 86,
  },

  {
    imageUrl: 'https://cdn.simpleicons.org/docker',
    title: 'Docker',
    color: '#2496ed',
    segment: 'devops',
    level: 82,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/git',
    title: 'Git',
    color: '#f15032',
    segment: 'devops',
    level: 87,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/googlecloud',
    title: 'GCP',
    color: '#4285f4',
    segment: 'devops',
    level: 61,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/githubactions',
    title: 'Github Actions',
    color: '#2088ff',
    segment: 'devops',
    level: 84,
  },
  {
    imageUrl: 'svgs/aws.svg',
    title: 'AWS',
    color: '#ff9901',
    segment: 'devops',
    level: 33,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/redux',
    title: 'Redux',
    color: '#764abd',
    segment: 'libs',
    level: 92,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/prisma',
    title: 'Prisma',
    color: '#2d3748',
    segment: 'libs',
    level: 89,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/reduxsaga',
    title: 'Redux Saga',
    color: '#999999',
    segment: 'libs',
    level: 92,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/reactquery',
    title: 'React Query',
    color: '#ff4154',
    segment: 'libs',
    level: 88,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/reacttable',
    title: 'React Table',
    color: '#ff4154',
    segment: 'libs',
    level: 87,
  },
  {
    imageUrl: '/svgs/zustand.svg',
    title: 'Zustand',
    color: '#f56d2e',
    segment: 'libs',
    level: 89,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/mui',
    title: 'MUI',
    color: '#007fff',
    segment: 'libs',
    level: 89,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/antdesign',
    title: 'Ant Design',
    color: '#0271fe',
    segment: 'libs',
    level: 85,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/tailwindcss',
    title: 'Tailwind CSS',
    color: '#06b6d5',
    segment: 'libs',
    level: 91,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/bootstrap',
    title: 'Bootstrap',
    color: '#7952b3',
    segment: 'libs',
    level: 72,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/styledcomponents',
    title: 'Styled Components',
    color: '#dc7094',
    segment: 'libs',
    level: 89,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/sass',
    title: 'Sass',
    color: '#cc6699',
    segment: 'libs',
    level: 91,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/lottieFiles',
    title: 'LottieFiles',
    color: '#01ddb3',
    segment: 'libs',
    level: 79,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/shadcnui/FFF',
    title: 'Shadcn UI',
    color: '#fff',
    segment: 'libs',
    level: 87,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/express/FFF',
    title: 'Express',
    color: '#fff',
    segment: 'libs',
    level: 77,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/fastify/FFF',
    title: 'Fastify',
    color: '#fff',
    segment: 'libs',
    level: 73,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/axios',
    title: 'Axios',
    color: '#5a29e4',
    segment: 'libs',
    level: 87,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/jquery',
    title: 'jQuery',
    color: '#076aae',
    segment: 'libs',
    level: 69,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/reactrouter',
    title: 'React Router',
    color: '#ca4245',
    segment: 'libs',
    level: 89,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/sharp',
    title: 'Sharp',
    color: '#99cd00',
    segment: 'libs',
    level: 84,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/storybook',
    title: 'Storybook',
    color: '#ff4885',
    segment: 'libs',
    level: 85,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/swagger',
    title: 'Swagger',
    color: '#85eb2c',
    segment: 'libs',
    level: 89,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/vite',
    title: 'Vite',
    color: '#646dff',
    segment: 'libs',
    level: 77,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/npm',
    title: 'npm',
    color: '#cb3838',
    segment: 'libs',
    level: 84,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/yarn',
    title: 'Yarn',
    color: '#2d8ebb',
    segment: 'libs',
    level: 87,
  },
  {
    imageUrl: 'https://cdn.simpleicons.org/pnpm',
    title: 'pnpm',
    color: '#f69221',
    segment: 'libs',
    level: 72,
  },
];
